version: '3.8'

services:
  networkup-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: networkup_nextjs_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000